version: '3.7'

services:
  db:
    container_name: covid-reservation-system-mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: covid-reservation-system
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d:ro

  external:
    container_name: covid-reservation-system-external
    build:
      context: ../external
      dockerfile: external-system.Dockerfile
    image: covid-reservation-system-external:1.0
    environment:
      TZ: Asia/Singapore
      NODE_ENV: production
    ports:
      - "6000:8000"
